### ISSUE TITLE
生成的二维码无法扫描登录

### ISSUE THREAD

**Issue by sun2ot** [isnl/wechat-robot#5]
![图片](https://user-images.githubusercontent.com/84566015/141307344-15b22859-d1a0-4709-8739-fd03f364120e.png)
如图。。。

**Comment by RopeHuo** [comment]
换个命令行工具试试吧，我现在是扫了，手机上提示可以登录，但是登陆失败了。

**Comment by sun2ot** [comment]
我已收到您的邮件，当我看到注意到时会尽快阅览。如有需要将会立即回复您！I have received your email and will read it as soon as I see it. If necessary,I will reply you immediately!
